name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest
    env:
      PORT: ${{secrets.PORT}}
      DEBUG: ${{secrets.DEBUG}}

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
